- name: This sets up an include test
  hosts: dev
  tasks:
  - debug:
      msg: calling from main on RHEL
    when: ansible_os_family == "RedHat"
  - debug:
      msg: calling from main on  UBUNTU
    when: ansible_os_family == "Debian"

- name: Include a play after another play
  import_playbook: second.yaml

- name: Include a play after another play
  import_playbook: third.yaml

