- name: This sets up an include test
  hosts: dev
  vars:
    myname: singaravelan
    age: 23
  tasks:
  - debug:
      msg: calling from second on RHEL
    when: ansible_os_family == "RedHat"
  - debug:
      msg: calling from second on  UBUNTU
    when: ansible_os_family == "Debian"
