---
- name: Installing Apache MSI
  hosts: windows

  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\\Lakshminarayanan\\httpd-2.2.25-win32-x86-no_ssl.msi

    - name: Install MSI
      win_package:
        path: C:\\Lakshminarayanan\\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
    - name: Create a new service with extra details
      win_service:
        name: service name
        path: C:\\Program Files (x86)\\Apache Software Foundation\\Apache2.2\\bin\httpd.exe
        display_name: Apacte2.2
        description: A test service description
    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: Apache2.2
        start_mode: auto
        state: started
        username: LocalSystem
        password: ''
        dependency_action: remove

