---
- name: This is to create Group

  hosts: web	
  tasks:
  - name: Create a group
    group: name=deploy1 state=present

- name: This play to create user
  hosts: web	
  tasks: 
  - name: Create a User
    user: name=deploy-user2 shell=/bin/bash group=deploy1

- name: This play to create httpd package
  hosts: web	
  tasks: 
  - name: Create a httpd package
    yum: name=httpd state=present

- name: This play to enable and start httpd service
  hosts: web	
  tasks: 
  - name: Create a httpd package
    service: name=httpd enabled=yes state=started

- name: This play to create index.html
  hosts: web	
  tasks: 
  - name: create index.html file
    file: path=/var/www/html/index1.html state=touch mode=u=rw,g=r,o=r

- name: This play to create package called git & wget
  hosts: web	
  tasks: 
  - name: Create package for Git & Wget
    package: name=git,wget state=present

- name: This play to create package called git & wget
  hosts: web	
  tasks: 
  - name: Create clone git repo
    git: repo=https://github.com/scmgalaxy/ansible-role-template clone=yes dest=/home/cloud-user/ansible-role-template

- name: This play to reboot machine
  hosts: web	
  tasks: 
  - name: reboot remote server 	
    reboot: 
...	
