# Write a Ansible Playbook to create a group called “deploy”

- name: deploy user and group
  hosts: localhost
  tasks:
  - name: Add group "deploy"
    group: name=deploy
    become: true

# Write a Ansible Playbook to create a user called “deploy-user” which is part of group called “group” and with /bin/bash shell.

  - name: Add user "deploy-user"
    user: name=deploy-user groups=deploy password="" shell=/bin/bash append=yes  state=present
    become: true

# Write a Ansible Playbook to install package named “httpd” in RHEL/centos.
# Write a Ansible Playbook to start and enable the service named “httpd”

- name: Deploying a webserver and start it
  hosts: locahost
  tasks:
  - name: Deploy a webserver
    yum: name=httpd state=present
  - name: starting the httpd server
    service: name=httpd state=started

# Write a Ansible Playbook to reboot a self machine.
- name: Rebooting the hosts
  hosts: localhost
  tasks:
  - name: Rebooting now.
    reboot:

# Write a Ansible Playbook to install a package called git, wget.
- name: Installing git and wget.
  hosts: localhost
  tasks:
  - name: Installing .....
    yum: name={{item}} state=present
    with_items:
     - wget
     - git
# Write a Ansible Playbook to clone git repo. thttps://github.com/scmgalaxy/ansible-role-template
- name: Cloning git repo https://github.com/scmgalaxy/ansible-role-template
  hosts: localhost
  environment:
      http_proxy: 'http://web-proxy:8080'
      https_proxy: 'http://web-proxy:8080'
  tasks:
  - name: cloning....
    git: repo=https://github.com/scmgalaxy/ansible-role-template clone=yes dest=./ansible-role-template

