
#how to declare a variable playbook
#--------------------------------
---
- name: This sets up an httpd webserver
  hosts: web
  vars:
    myname: Sridhar

  tasks:
  - name: Install the httpd apps
    yum: name=httpd state=present
  - name: start the httpd service
    service: name=httpd state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - debug:
      msg: My Name is {{ myname }} 
...

#templates
#=========================
#templates would help you to change intrro* vars dynamically.

#Python - Jinja2

#Step 1- Convert a template file info .j2
#Step 2 - Declare any var which you want to change during run time in .j2
#Step 3 - using Module called "template"


---

- name: This sets up an httpd webserver
  hosts: web
  vars:
    myname: Sridhar
    port: 81

  tasks:
  - name: Install the httpd apps
    yum: name=httpd state=present
  - name: start the httpd service
    service: name=httpd state=stopped
  - name: Template a file to httpd.conf.j2
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
  - name: start the httpd service
    service: name=httpd state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: Template a file to index.html.j2
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
  - debug:
      msg: My Name is {{ myname }} 

...
