
- name: Creating deploy user and group
  hosts: web
  tasks:
  - name: Add group "deploy"
    group: name=deploy
    become: true

  - name: Add user "deploy-user"
    user: name=deploy-user groups=deploy password="" shell=/bin/bash append=yes  state=present
    become: true

- name: Deploying a webserver and start it
  hosts: web
  tasks:
  - name: Deploying a webserver
    yum: name=httpd state=present
  - name: starting the httpd server
    service: name=httpd state=started



- name: create an index.html for the webserver.
  hosts: web
  tasks:
  - name: touch the index file
    file:
      path: /var/www/html/index.html
      mode: 644
      state: touch

  - name: adding contents to indexfile
    blockinfile:
      dest: /var/www/html/index.html
      block: |
        <html>
        <h1> Welcome to HP Ansible class </h1>
        </html>


- name: Rebooting the hosts
  hosts: web
  tasks:
  - name: Rebooting now.
    reboot:


- name: Installing git and wget.
  hosts: web
  tasks:
  - name: Installing .....
    yum: name={{item}} state=present
    with_items:
     - wget
     - git

- name: Cloning git repo https://github.com/scmgalaxy/ansible-role-template
  hosts: web
  tasks:
  - name: cloning....
    git: repo=https://github.com/scmgalaxy/ansible-role-template clone=yes dest=./ansible-role-template


