---
- name: reboot localhost
  hosts: web
  tasks:
   - name: Restart Server
     shell: sleep 2 && shutdown -r now
     async: 1
     poll: 0
     become: yes
     become_method: sudo
     ignore_errors: true
