---
- name: This is to create Group
  hosts: web	
  tasks:
  - name: Create a group
    group: name=deploy1 state=present

- name: This play to create user
  hosts: web	
  tasks: 
  - name: Create a User
    user: name=deploy-user1 shell=/bin/bash group=deploy1

- name: This play to create httpd package
  hosts: web	
  tasks: 
  - name: Create a httpd package
    yum: name=httpd state=present

- name: This play to start httpd service
  hosts: web	
  tasks: 
  - name: start httpd service
    service: name=httpd state=started

- name: This play to create index.html
  hosts: web	
  tasks: 
  - name: create index.html
    file: name=index1.html path=/var/www/html state=touch

- name: This play to install package
  hosts: web	
  tasks: 
  - name: install package
    yum: name=git,wget state=present

- name: This play to clone the git software
  hosts: web	
  tasks: 
  - name: clone gi
    git: clone=yes repo=https://github.com/scmgalaxy/ansible-role-template dest=/home/cloud-user/ansible-role-template

- name: This play to create Reboot the host
  hosts: web	
  tasks: 
  - name: Reboot the machine
    reboot: reboot_timeout=10 
...
