---
- name: This sets up an httpd webserver
  hosts: localhost
  vars:
    service: httpd 

  tasks:
  - name: Install the httpd apps
    yum: name={{ service }} state=present
  - name: start the httpd service
    service: name={{ service }} state=started

