---
- name: This sets up an httpd webserver
  hosts: web
  vars_prompt:
    - name: "service"
      prompt: "Which service Do you want to install?"
      private: no 
  tasks:
  - name: Install the httpd apps
    yum: name={{ service }} state=present
  - name: start the httpd service
    service: name={{ service }} state=started

