---
- name: This sets up an httpd webserver
  hosts: localhost

  tasks:
  - ec2:
      key_name: rajesh-mumbai
      instance_type: t2.small
      image: ami-5b673c34
      instance_tags:
        Name: DEMO
      vpc_subnet_id: subnet-8c19b3e5
      region: ap-south-1
