- name: This sets up an httpd webserver
  hosts: web

  roles:
    - role: web
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk


