---
- name: This sets up an httpd webserver
  hosts: localhost
  vars_files:
    - "vars.yaml"
  tasks:
  - name: Install the httpd apps
    yum: name={{name}} state=present
  - name: start the httpd service
    service: name={{name}} state=started
  - name: copy files
    copy: src={{src}} dest={{dest}}
